# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdnote_site', '0005_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('kill', models.IntegerField()),
                ('death', models.IntegerField()),
                ('win', models.BooleanField()),
                ('rule', models.CharField(choices=[('FR', 'フラッグ戦'), ('EL', '全滅戦'), ('GR', '大将戦'), ('RE', '復活戦'), ('ME', 'メディック戦'), ('SP', 'スパイ戦'), ('OD', '攻守戦'), ('HG', 'ハンドガン戦'), ('FX', 'キツネ狩り'), ('RE', ' リアルカウント戦')], default='FR', max_length=2)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(default='DEFAULT NAME', max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kdnote_site.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
